### ISSUE TITLE
Issues with the next version of ggplot2

### ISSUE THREAD

**Issue by thomasp85** [ashenoy-cmbi/grafify#3]
Hi

We are in the process of preparing the next release of ggplot2 and our reversen dependency tests show an issue with grafify. The core of the issue seems to be that the ggplot2 calls are full of double braces where they have no meaning, and internal changes have now made this an error. To be clear, this is not a change in functionality, rather before the use of double braces were a no-op, where-as now they throw an error. There are very few places were tidy evaluation makes sense in ggplot2 and where double braces are meaningful, and those are inside `aes()` and inside `vars()`.

We plan to submit ggplot2 by the end of October and hope you can provide a fix in time

kind regards
Thomas

**Comment by ashenoy-cmbi** [comment]
Dear Thomas,
Thanks for the heads up and the hint. I’m not that much of a coder tbh, but I think I understand what you mean. I can now see there is no reason for {{ outside aes() calls. Rest of the variables from grafify wrappers could be passed to ggplot2 as is from the call!

I was in the process of updating some other parts of grafify, so will try and update this.

Many thanks,
Avinash

From: Thomas Lin Pedersen ***@***.***>
Sent: 07 October 2022 11:40
To: ashenoy-cmbi/grafify ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ashenoy-cmbi/grafify] Issues with the next version of ggplot2 (Issue #3)

This email from ***@***.*** originates from outside Imperial. Do not click on links and attachments unless you recognise the sender. If you trust the sender, add them to your safe senders list<https://spam.ic.ac.uk/SpamConsole/Senders.aspx> to disable email stamping for this address.



Hi

We are in the process of preparing the next release of ggplot2 and our reversen dependency tests show an issue with grafify. The core of the issue seems to be that the ggplot2 calls are full of double braces where they have no meaning, and internal changes have now made this an error. To be clear, this is not a change in functionality, rather before the use of double braces were a no-op, where-as now they throw an error. There are very few places were tidy evaluation makes sense in ggplot2 and where double braces are meaningful, and those are inside aes() and inside vars().

We plan to submit ggplot2 by the end of October and hope you can provide a fix in time

kind regards
Thomas

**Comment by thomasp85** [comment]
Thank you for the quick reply. Let me know if there are any issues

**Comment by ashenoy-cmbi** [comment]
Hi Thomas, I updated grafify to v3.0.0. Could you let me know whether this still shows up errors with ggplot2? If so, I'll look into fixing them. 
Thanks,
Avinash

**Comment by ashenoy-cmbi** [comment]
Hi Thomas, looks like grafify is working OK - so I'm going to close this particular issue.
